# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[31,32)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
# The mod license
license="KML (Keksuccino Mod License)"
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
# The modid of the mod
modId="fancymenu" #mandatory
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
version="2.2.0" #mandatory
 # A display name for the mod
displayName="FancyMenu" #mandatory
# A text field displayed in the mod UI
authors="Keksuccino" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''Give your life a fancy touch. You deserve it.

COPYRIGHT:

> FancyMenu Â© Copyright 2020-2021 Keksuccino.
  FancyMenu is licensed under KML.
  See https://github.com/Keksuccino/FancyMenu/blob/master/LICENSE.md for more infos about this license.'''

[[dependencies.fancymenu]]
modId="konkrete"
mandatory=true
ordering="NONE"
versionRange="[1.1.6,)"
side="BOTH"

[[dependencies.fancymenu]]
modId="findme"
mandatory=false
ordering="AFTER"
side="BOTH"

[[dependencies.fancymenu]]
modId="forge"
mandatory=true
versionRange="[31.2.49,)"
ordering="NONE"
side="BOTH"
