# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[${neoforge_loader_version},)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
# The mod license
license="${mod_license}"
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
# The modid of the mod
modId="${mod_id}" #mandatory
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
version="${mod_version}" #mandatory
# A display name for the mod
displayName="${mod_name}" #mandatory
# A text field displayed in the mod UI
authors="${mod_authors}" #optional
logoFile="fancymenu_logo_128x128.png"
# The description text for the mod (multi line!) (#mandatory)
description='''${mod_description}'''

[[mixins]]
config = "${mod_id}.mixins.json"
[[mixins]]
config = "${mod_id}.neoforge.mixins.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies.${mod_id}]]
modId="konkrete"
type="required"
ordering="NONE"
versionRange="[1.9.4,)"
side="BOTH"

[[dependencies.${mod_id}]]
modId="melody"
type="required"
ordering="NONE"
versionRange="[1.0.6,)"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="findme"
type="optional"
ordering="AFTER"
versionRange="[1.0.0,)"
side="BOTH"

[[dependencies.${mod_id}]]
modId="drippyloadingscreen"
type="optional"
ordering="NONE"
versionRange="[3.0.0,)"
side="BOTH"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neoforge_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version},)"
ordering="NONE"
side="BOTH"